version: "3.9"

# extension field: https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-networks: &networks
  networks:
    - yalc-network

services:
  yalc-database:
    <<: *networks
    image: mysql:8.3
    restart: unless-stopped
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-63306}:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD:-password}
    volumes:
      - type: volume
        source: yalc-database
        target: /var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 40s
      retries: 20

  phpmyadmin:
    <<: *networks
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    # profiles: [ dev ]

volumes:
  yalc-database:


networks:
  yalc-network:
